name: Riot API Daily Sync Trator

on:
  schedule:
    - cron: '0 7 * * *'    # 07:00 UTC = 04:00 BRT (coleta da madrugada)
    - cron: '30 20 * * *'  # 20:30 UTC = 17:30 BRT (alimenta o relatório das 19:00)
  workflow_dispatch:

jobs:
  sync-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Execute Trator Script
        run: node cron/sync.js
        env:
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          D1_DATABASE_ID: ${{ secrets.D1_DATABASE_ID }}

      # ARTEFATOS:
      - name: Compactar e Fazer Upload dos Arquivos de Log
        if: always() # Garante que os relatórios subam mesmo se o script der algum erro no meio do caminho
        uses: actions/upload-artifact@v4
        with:
          name: Relatorios-Historico-Jogadores-D1
          path: logs/
          retention-days: 7 # Os relatórios ficam guardados no GitHub por 7 dias