name: Riot API Daily Sync Trator

on:
  schedule:
    - cron: '30 3 * * *' # 3:30 UTC = 00:30 da manhã no horário de Brasília
  workflow_dispatch: # Libera o botão no site do GitHub para testar manualmente

jobs:
  sync-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Execute Trator Script
        run: node cron/sync.js
        env:
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          D1_DATABASE_ID: ${{ secrets.D1_DATABASE_ID }}